version: '3.7' # Manteniendo tu versión original

services:
   app:
      build: .
      container_name: mi_django_app
      depends_on:
         - bd      
      environment:
         SECRET_KEY: ${SECRET_KEY}
         DB_NAME: ${DB_NAME} 
         DB_USER: ${DB_USER}
         DB_PASSWORD: ${DB_PASSWORD}
         DB_HOST: bd
         DB_PORT: ${DB_PORT}
         DJANGO_SETTINGS_MODULE: proy.settings
         PYTHONUNBUFFERED: 1
         TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
         TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
         MASTER_KEY: ${MASTER_KEY}
      volumes:
        - .:/app
        - ./.ssh_keys/id_rsa:/root/.ssh/id_rsa:ro 
        - static_data_mi_app:/var/www/staticfiles
      deploy:
         resources:
            limits:
               cpus: "2"
               memory: "1024M"      

   bd:
      image: mariadb:10.11
      container_name: mi_mariadb
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         MYSQL_DATABASE: ${DB_NAME}         
         MYSQL_USER: ${DB_USER}             
         MYSQL_PASSWORD: ${DB_PASSWORD}     
      volumes:
         - mysql_data_mi_app:/var/lib/mysql 
         - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql 
      deploy:
         resources:
            limits:
               cpus: "2"
               memory: "1024M"      

   nginx:
      image: nginx:alpine
      container_name: mi_nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - static_data_mi_app:/var/www/staticfiles
        - ./certificados:/certificados:ro
      depends_on:
        - app
      deploy:
         resources:
            limits:
               cpus: "2"
               memory: "1024M"      

volumes:
  mysql_data_mi_app: {}
  static_data_mi_app: {}
