# Generated by Django 4.2.7 on 2023-12-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=15)),
                ('avala', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usuario_remoto', models.CharField(max_length=50)),
                ('llave_publica', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorio_origen', models.CharField(max_length=255)),
                ('directorio_destino', models.CharField(max_length=255)),
                ('periodicidad', models.CharField(max_length=50)),
                ('server_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respaldos_destino', to='backend.server')),
                ('server_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respaldos_origen', to='backend.server')),
            ],
        ),
    ]
