# Generated by Django 4.2.7 on 2023-12-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=15)),
                ('avala', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usuario_remoto', models.CharField(max_length=50)),
                ('llave_publica', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BackupConfig',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
