# Generated by Django 4.2.7 on 2023-12-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_server1_delete_backupconfig_delete_server'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server1',
            new_name='Server',
        ),
    ]
