# Generated by Django 4.2.7 on 2023-12-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_server1_delete_backupconfig_delete_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorio_origen', models.CharField(max_length=255)),
                ('directorio_destino', models.CharField(max_length=255)),
                ('periodicidad', models.CharField(max_length=50)),
                ('server_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respaldos_destino', to='backend.server1')),
                ('server_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respaldos_origen', to='backend.server1')),
            ],
        ),
    ]
