# Generated by Django 4.2.7 on 2023-12-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_backupconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server1',
            name='exitoso',
        ),
    ]
