# Generated by Django 3.2.19 on 2023-12-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_server1_exitoso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server1',
            name='llave_publica',
        ),
        migrations.RemoveField(
            model_name='server1',
            name='password',
        ),
    ]
