# Generated by Django 4.2.7 on 2023-12-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_backupconfig_server_remitente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupconfig',
            old_name='server_remitente',
            new_name='server_re',
        ),
    ]
