# Generated by Django 3.2.19 on 2023-12-21 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_server_remitente_backupconfig_server_re'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupconfig',
            old_name='server_re',
            new_name='server_remitente',
        ),
    ]
