# Generated by Django 3.2.19 on 2023-12-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_server_re_backupconfig_server_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfig',
            name='comando_cron',
            field=models.TextField(blank=True, null=True),
        ),
    ]
