# Generated by Django 3.2.19 on 2023-12-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_backupconfig_comando_cron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupconfig',
            name='comando_cron',
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
