# Generated by Django 3.2.19 on 2023-12-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20231224_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupconfig',
            name='comment',
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='comando_cron',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
