# Generated by Django 3.2.19 on 2023-12-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20231225_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfig',
            name='comando_cron',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
