# Generated by Django 3.2.19 on 2023-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_backupconfig_comando_cron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfig',
            name='comando_cron',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
