# Generated by Django 5.2 on 2025-05-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_otpattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupConfig',
        ),
    ]
