# Generated by Django 5.2 on 2025-05-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_delete_backupconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpattempt',
            old_name='locked_until',
            new_name='bloqueado',
        ),
        migrations.RenameField(
            model_name='otpattempt',
            old_name='attempts',
            new_name='intentos',
        ),
        migrations.RenameField(
            model_name='otpcode',
            old_name='created_at',
            new_name='creado',
        ),
    ]
