# Generated by Django 5.2 on 2025-05-19 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_rename_locked_until_otpattempt_bloqueado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPAttempt',
            new_name='OTPIntento',
        ),
    ]
