# Generated by Django 5.2 on 2025-06-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_servidor_servicioconfigurado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server1',
        ),
    ]
