# Generated by Django 5.2 on 2025-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_delete_server1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='direccion_host',
            field=models.CharField(help_text='La dirección IP (ej: 192.168.1.10) o el nombre de dominio completo (ej: servidor.midominio.com) del servidor.', max_length=255, unique=True, verbose_name='Dirección IP o Dominio'),
        ),
    ]
