# Generated by Django 5.2 on 2025-06-16 08:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_servidor_direccion_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicioconfigurado',
            options={'ordering': ['servidor__nombre', 'nombre_servicio_remoto'], 'verbose_name': 'Servicio Configurado', 'verbose_name_plural': 'Servicios Configurados'},
        ),
        migrations.RemoveField(
            model_name='servicioconfigurado',
            name='comando_bajar',
        ),
        migrations.RemoveField(
            model_name='servicioconfigurado',
            name='comando_levantar',
        ),
        migrations.RemoveField(
            model_name='servicioconfigurado',
            name='comando_reiniciar',
        ),
        migrations.RemoveField(
            model_name='servicioconfigurado',
            name='comando_verificar_estado',
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='configurado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_que_configuro', to=settings.AUTH_USER_MODEL, verbose_name='Configurado por'),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='descripcion_personalizada',
            field=models.TextField(blank=True, verbose_name='Descripción Personalizada'),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='estado_conocido',
            field=models.CharField(choices=[('desconocido', 'Desconocido'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('error_verificacion', 'Error al Verificar')], default='desconocido', max_length=20, verbose_name='Último Estado Conocido'),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='fecha_configuracion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='habilitado_para_gestion',
            field=models.BooleanField(default=True, verbose_name='¿Habilitado para Gestión desde Plataforma?'),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='log_ultima_accion',
            field=models.TextField(blank=True, verbose_name='Log de la Última Acción'),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='nombre_servicio_remoto',
            field=models.CharField(help_text='El nombre real del servicio en systemd (ej: nginx.service, mysql.service).', max_length=100, verbose_name='Nombre del Servicio en el Servidor'),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='puerto_monitorizar',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Puerto a Monitorizar (Opcional)'),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='ultima_actualizacion_config',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='ultima_comprobacion_estado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Última Comprobación'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='direccion_host',
            field=models.GenericIPAddressField(help_text='La dirección IPv4 o IPv6 del servidor.', unique=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Administrador que registró'),
        ),
    ]
