# Generated by Django 5.2 on 2025-06-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_servicioconfigurado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'password_sudo', 'api_key_grafana'", max_length=100)),
                ('valor_cifrado', models.BinaryField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='backend.servidor')),
            ],
            options={
                'unique_together': {('servidor', 'nombre')},
            },
        ),
    ]
