# Generated by Django 5.2 on 2025-06-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='clave_ssh_configurada',
        ),
    ]
