# Generated by Django 5.2 on 2025-06-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_remove_servidor_clave_ssh_configurada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secret',
        ),
    ]
