# Generated by Django 5.2 on 2025-06-18 12:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_delete_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicioconfigurado',
            options={'verbose_name': 'Servicio Configurado', 'verbose_name_plural': 'Servicios Configurados'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['nombre'], 'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
        migrations.RemoveField(
            model_name='servicioconfigurado',
            name='configurado_por',
        ),
        migrations.RemoveField(
            model_name='servicioconfigurado',
            name='fecha_configuracion',
        ),
        migrations.RemoveField(
            model_name='servicioconfigurado',
            name='habilitado_para_gestion',
        ),
        migrations.RemoveField(
            model_name='servicioconfigurado',
            name='puerto_monitorizar',
        ),
        migrations.RemoveField(
            model_name='servicioconfigurado',
            name='ultima_actualizacion_config',
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='estado_conocido',
            field=models.CharField(choices=[('desconocido', 'Desconocido'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('error_verificacion', 'Error al Verificar')], default='desconocido', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='nombre_servicio_remoto',
            field=models.CharField(max_length=100, verbose_name='Nombre del Servicio en systemd'),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_configurados', to='backend.servidor'),
        ),
        migrations.AlterField(
            model_name='servicioconfigurado',
            name='ultima_comprobacion_estado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='detalles_adicionales',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles Adicionales'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='direccion_host',
            field=models.GenericIPAddressField(unique=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Servidor'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='usuario_remoto',
            field=models.CharField(max_length=50, verbose_name='Usuario Remoto SSH'),
        ),
    ]
