# Generated by Django 5.2 on 2025-06-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_servicioconfigurado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='detalles_adicionales',
        ),
    ]
