# Generated by Django 5.2 on 2025-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_remove_servidor_detalles_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioconfigurado',
            name='habilitado_para_gestion',
            field=models.BooleanField(default=True, help_text='Si está marcado, se mostrarán los botones de levantar, bajar y reiniciar.', verbose_name='¿Gestión Habilitada?'),
        ),
    ]
